# Generated by Django 4.0.5 on 2022-06-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=120)),
                ('designation', models.CharField(max_length=120)),
                ('salary', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('experience', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
